---
- name: nextcloud docker container
  docker_container:
    name: nextcloud_app
    image: "wonderfall/nextcloud:{{ nextcloud_version }}"
    state: started
    recreate: yes
    links: nextcloud_db:nextcloud_db
    volumes:
      - "{{ nextcloud_config }}:/config"
      - "{{ nextcloud_apps }}:/apps2"
      - "{{ redis }}:/var/lib/redis"
      - "{{ nextcloud_data }}:/data"
    env:
      DB_TYPE: "mysql"
      DB_NAME: "nextcloud"
      DB_HOST: "nextcloud_db"
      DB_USER: "{{ mysql_application_user }}"
      DB_PASSWORD: "{{ nextcloud_db_password  }}"
      ADMIN_USER: "{{ nextcloud_admin_user }}"
      ADMIN_PASSOWRD: "{{ nextcloud_admin_password }}"
