macosx:
  hosts:
      localhost:
          ansible_connection=local
ferryfive:
  hosts:
      int.budlight.kasten.beer:
      int.budweiser.kasten.beer:

online:
  hosts:
      int.redstripe.kasten.beer:
          ansible_port=2222
          ansible_host=192.168.27.1
      dorada.kasten.beer:
