---
- name: mysql docker container
  docker_container:
    name: "{{ mysql_instance_name }}"
    image: "mysql:{{ mysql_version }}"
    state: started
    recreate: yes
    pull: true
    volumes:
    - "{{ mysql_host_path }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_application_user }}"
      MYSQL_PASSWORD: "{{ mysql_application_password }}"

# TODO
# script for mysqldump
# variable
# mysql_dump: /opt/nextcloud/mysql/dumps/  mysql_instance_name: mysql
