---
- name: mysql docker container
  docker_container:
    name: "{{ mysql_instance_name }}"
    image: "mysql:{{ mysql_version }}"
    state: started
    pull: true
    links: "{{ mysql_container_links }}"
    volumes:
    - "{{ mysql_host_path }}:/var/lib/mysql"

# TODO
# script for mysqldump
# variable
# mysql_dump: /opt/nextcloud/mysql/dumps/  mysql_instance_name: mysql
