---
- hosts: int.node-1.nc.mschnitzius.com
  become_method: sudo
  become: yes

  pre_tasks:
  - name: create zfs dataset
    command: zfs create tank/docker/data/nextcloud -o mountpoint=/opt/nextcloud
    ignore_errors: True

  roles:
   - docker-arch
   - mysql-docker
   - nextcloud-docker
