---
- name: Install docker and pip for ansible management
  pacman: name={{item}}
  with_items:
       - docker
       - python2-pip
       - python2

- name: install pip packages for ansible
  pip: name= "{{ item }}" executable=/usr/bin/pip2
  become: true
  with_items:
    - setuptools
    - docker-py
    - python-psycopg2
